### ISSUE TITLE
Set the logo to the social preview

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/aqua#407]
* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview
* #403
* https://github.com/suzuki-shunsuke/aqua/tree/main/logo

You have to fix the size of image file properly

> Images should be at least 640×320px (1280×640px for best display).

![image](https://user-images.githubusercontent.com/13323303/142715106-c500a0c5-f3aa-4465-a217-cc1feaf244d4.png)

cc: @vadasambar

**Comment by vadasambar** [comment]
![aqua1280x640](https://user-images.githubusercontent.com/34534103/143281369-e2a02538-0a46-4a28-a34f-d23ce03c4560.png)
This ^ should work (I have set the size to 1280x640px)

**Comment by suzuki-shunsuke** [comment]
@vadasambar Thank you so much!
I set the social preview to the image.

It looks cool.

![image](https://user-images.githubusercontent.com/13323303/143320543-bf8db533-e524-484d-add3-199fef092941.png)
